const projects = [
  {
    name: "Guess the City Game",
    link: "projects/Guess-City-Game",
    gitlink: "https://github.com/bernadette-estacio/Guess-The-City-Game-App",
    photo: "/assets/img/portfolio/guess-the-city.png",
    categories: "app react",
  },
  {
    name: "Find the Ghost Game",
    link: "projects/Ghost-Game",
    gitlink: "https://github.com/bernadette-estacio/ghost-game-react-app",
    photo: "/assets/img/portfolio/find-ghost-game.png",
    categories: "app react",
  },
  {
    name: "Pop the Bubbles Game",
    link: "projects/Pop-Game",
    gitlink: "https://github.com/bernadette-estacio/pop-game-react-app",
    photo: "/assets/img/portfolio/pop-bubbles-game.png",
    categories: "app react",
  },
  {
    name: "Kill the Fly Game",
    link: "projects/Kill-the-Fly",
    gitlink: "https://github.com/bernadette-estacio/fly-game-react-app",
    photo: "/assets/img/portfolio/kill-fly-game.png",
    categories: "app react",
  },
  {
    name: "Cats & Dogs Game",
    link: "projects/CatsnDogs-Game/CatsDogs",
    gitlink: "https://github.com/bernadette-estacio/CatsnDogs-Game-App",
    photo: "/assets/img/portfolio/cats-&-dogs.png",
    categories: "app",
  },
  {
    name: "Fortune Cookie App",
    link: "projects/Fortune-Cookie",
    gitlink: "https://github.com/bernadette-estacio/fortune-cookie-react-app",
    photo: "/assets/img/portfolio/fortune-cookie.png",
    categories: "app react",
  },
  {
    name: "Birth Month Meaning App",
    link: "projects/Birth-Month-Meaning",
    gitlink:
      "https://github.com/bernadette-estacio/Birth-Month-Meaning-React-App",
    photo: "/assets/img/portfolio/birth-month-meaning.png",
    categories: "app react",
  },
  {
    name: "Old Portfolio Website",
    link: "https://bernadette-estacio.netlify.app/",
    gitlink: "https://github.com/bernadette-estacio/My-Portfolio-Website",
    photo: "/assets/img/portfolio/old-portfolio.png",
    categories: "website angular",
  },
  {
    name: "Dental Website",
    link: "https://www.fortinodental.com/",
    gitlink: "https://github.com/bernadette-estacio/FortinoDental",
    photo: "/assets/img/portfolio/dental-website.png",
    categories: "website angular",
  },
  {
    name: "Nail Salon Website",
    link: "http://www.nailtropics.com/",
    gitlink: "https://github.com/bernadette-estacio",
    photo: "/assets/img/portfolio/nail-tropics.png",
    categories: "website wordpress",
  },
  {
    name: "Food Services Website",
    link: "https://andoks.com.ph/",
    gitlink: "https://github.com/bernadette-estacio",
    photo: "/assets/img/portfolio/andoks.png",
    categories: "website wordpress",
  },
  {
    name: "Restaurant Website",
    link: "https://www.ippudoph.com/",
    gitlink: "https://github.com/bernadette-estacio",
    photo: "/assets/img/portfolio/ippudo.png",
    categories: "website wordpress",
  },
  {
    name: "Restaurant Website",
    link: "http://www.sunniescafe.com/",
    gitlink: "https://github.com/bernadette-estacio",
    photo: "/assets/img/portfolio/sunnies-cafe.png",
    categories: "website wordpress",
  },
  {
    name: "Resort Website",
    link: "https://blueorchidresort.com/",
    gitlink: "https://github.com/bernadette-estacio",
    photo: "/assets/img/portfolio/blue-orchid.png",
    categories: "website wordpress",
  },
  {
    name: "Resort Website",
    link: "https://sunnyislandresort.com/",
    gitlink: "https://github.com/bernadette-estacio",
    photo: "/assets/img/portfolio/sunny-island.png",
    categories: "website wordpress",
  },
  {
    name: "Diving Resort Website",
    link: "https://scandidivers.com/",
    gitlink: "https://github.com/bernadette-estacio",
    photo: "/assets/img/portfolio/scandi-divers.png",
    categories: "website wordpress",
  },
  {
    name: "Corporate Website",
    link: "https://sfigroupofcompanies.com/",
    gitlink: "https://github.com/bernadette-estacio",
    photo: "/assets/img/portfolio/sfi.png",
    categories: "website wordpress",
  },
  {
    name: "Nail Salon Website",
    link: "http://www.kukolicious.website",
    gitlink: "https://github.com/bernadette-estacio/Kukolicious-Salon",
    photo: "/assets/img/portfolio/kukolicious.png",
    categories: "website react",
  },
  {
    name: "Hair Salon Website",
    link: "http://wwww.koronahairsalon.live",
    gitlink: "https://github.com/bernadette-estacio/Korona",
    photo: "/assets/img/portfolio/hair-salon.png",
    categories: "website angular",
  },
  {
    name: "Bakeshop Website",
    link: "https://www.panettiereyum.online",
    gitlink: "https://github.com/bernadette-estacio/Panettiere-Bakeshop",
    photo: "/assets/img/portfolio/bakeshop.png",
    categories: "website angular",
  },
  {
    name: "Real Estate Website",
    link: "https://www.dmcihomes.com/",
    gitlink: "https://github.com/bernadette-estacio/dmcicondomanila",
    photo: "/assets/img/portfolio/dmci.png",
    categories: "website react",
  },
  {
    name: "Periodontics Website",
    link: "https://www.drfortinoperiodontics.com",
    gitlink: "https://github.com/bernadette-estacio/FortinoPeriodontics",
    photo: "/assets/img/portfolio/periodontics.png",
    categories: "website",
  },
];

export default projects;
