const projects = [
  {
    name: "Portfolio Website",
    link: "https://bernadettecodes.vercel.app/",
    gitlink: "https://github.com/bernadette-codes/Bernadettecodes",
    photo:
      "https://raw.githubusercontent.com/bernadette-codes/Bernadettecodes/master/src/assets/img/portfolio/portfolio.png",
    categories: "website react",
  },
  {
    name: "Guess the City Game",
    link: "https://bernadettecodes.netlify.app/projects/guess-city-game/",
    gitlink: "https://github.com/bernadette-codes/Guess-The-City-Game-App",
    photo: "/assets/img/portfolio/guess-the-city.png",
    categories: "app react",
  },
  {
    name: "Find the Ghost Game",
    link: "https://bernadettecodes.netlify.app/projects/ghost-game/",
    gitlink: "https://github.com/bernadette-codes/Find-The-Ghost-Game-App",
    photo: "/assets/img/portfolio/find-ghost-game.png",
    categories: "app react",
  },
  {
    name: "Pop the Bubbles Game",
    link: "https://bernadettecodes.netlify.app/projects/pop-game/",
    gitlink: "https://github.com/bernadette-codes/pop-game-react-app",
    photo: "/assets/img/portfolio/pop-bubbles-game.png",
    categories: "app react",
  },
  {
    name: "Kill the Fly Game",
    link: "https://bernadettecodes.netlify.app/projects/kill-the-fly/",
    gitlink: "https://github.com/bernadette-codes/fly-game-react-app",
    photo: "/assets/img/portfolio/kill-fly-game.png",
    categories: "app react",
  },
  {
    name: "Cats & Dogs Game",
    link: "https://bernadettecodes.netlify.app/projects/catsndogs-game/catsdogs",
    gitlink: "https://github.com/bernadette-codes/CatsnDogs-Game-App",
    photo: "/assets/img/portfolio/cats-&-dogs.png",
    categories: "app",
  },
  {
    name: "Fortune Cookie App",
    link: "https://bernadettecodes.netlify.app/projects/fortune-cookie/",
    gitlink: "https://github.com/bernadette-codes/Fortune-Cookie-Message-App",
    photo: "/assets/img/portfolio/fortune-cookie.png",
    categories: "app react",
  },
  {
    name: "Birth Month Meaning App",
    link: "https://bernadettecodes.netlify.app/projects/birth-month-meaning/",
    gitlink: "https://github.com/bernadette-codes/Birth-Month-Personality-App",
    photo: "/assets/img/portfolio/birth-month-meaning.png",
    categories: "app react",
  },
  {
    name: "Old Portfolio Website",
    link: "https://bernadette-old-portfolio.netlify.app/",
    gitlink: "https://github.com/bernadette-codes/My-Portfolio-Website",
    photo: "/assets/img/portfolio/old-portfolio.png",
    categories: "website angular",
  },
  {
    name: "Dental Website",
    link: "https://www.fortinodental.com/",
    gitlink: "https://github.com/bernadette-codes/FortinoDental",
    photo: "/assets/img/portfolio/dental-website.png",
    categories: "website angular",
  },
  {
    name: "Nail Salon Website",
    link: "http://www.nailtropics.com/",
    gitlink: "https://github.com/bernadette-codes",
    photo: "/assets/img/portfolio/nail-tropics.png",
    categories: "website wordpress",
  },
  {
    name: "Food Services Website",
    link: "https://andoks.com.ph/",
    gitlink: "https://github.com/bernadette-codes",
    photo: "/assets/img/portfolio/andoks.png",
    categories: "website wordpress",
  },
  {
    name: "Restaurant Website",
    link: "https://www.ippudoph.com/",
    gitlink: "https://github.com/bernadette-codes",
    photo: "/assets/img/portfolio/ippudo.png",
    categories: "website wordpress",
  },
  {
    name: "Restaurant Website",
    link: "http://www.sunniescafe.com/",
    gitlink: "https://github.com/bernadette-codes",
    photo: "/assets/img/portfolio/sunnies-cafe.png",
    categories: "website wordpress",
  },
  {
    name: "Resort Website",
    link: "https://blueorchidresort.com/",
    gitlink: "https://github.com/bernadette-codes",
    photo: "/assets/img/portfolio/blue-orchid.png",
    categories: "website wordpress",
  },
  {
    name: "Resort Website",
    link: "https://sunnyislandresort.com/",
    gitlink: "https://github.com/bernadette-codes",
    photo: "/assets/img/portfolio/sunny-island.png",
    categories: "website wordpress",
  },
  {
    name: "Diving Resort Website",
    link: "https://scandidivers.com/",
    gitlink: "https://github.com/bernadette-codes",
    photo: "/assets/img/portfolio/scandi-divers.png",
    categories: "website wordpress",
  },
  {
    name: "Corporate Website",
    link: "https://sfigroupofcompanies.com/",
    gitlink: "https://github.com/bernadette-codes",
    photo: "/assets/img/portfolio/sfi.png",
    categories: "website wordpress",
  },
  {
    name: "Nail Salon Website",
    link: "http://www.kukolicious.website",
    gitlink: "https://github.com/bernadette-codes/Kukolicious-Salon",
    photo: "/assets/img/portfolio/kukolicious.png",
    categories: "website react",
  },
  {
    name: "Hair Salon Website",
    link: "http://wwww.koronahairsalon.live",
    gitlink: "https://github.com/bernadette-codes/Korona",
    photo: "/assets/img/portfolio/hair-salon.png",
    categories: "website angular",
  },
  {
    name: "Bakeshop Website",
    link: "https://www.panettiereyum.online",
    gitlink: "https://github.com/bernadette-codes/Panettiere-Bakeshop",
    photo: "/assets/img/portfolio/bakeshop.png",
    categories: "website angular",
  },
  {
    name: "Real Estate Website",
    link: "https://www.dmcihomes.com/",
    gitlink: "https://github.com/bernadette-codes/dmcicondomanila",
    photo: "/assets/img/portfolio/dmci.png",
    categories: "website react",
  },
  {
    name: "Periodontics Website",
    link: "https://www.drfortinoperiodontics.com",
    gitlink: "https://github.com/bernadette-codes/FortinoPeriodontics",
    photo: "/assets/img/portfolio/periodontics.png",
    categories: "website",
  },
];

export default projects;
