const tools = {
  CMS: {
    WordPress: "/assets/img/skills/wordpress.png",
    AEM: "/assets/img/tools/aem.png",
    Sitecore: "/assets/img/tools/sitecore.jpg",
    Pagebuilder: "/assets/img/tools/pagebuilder.png",
    Spacer: "/assets/img/tools/ampps.png",
  },
  "DevOps Tools": {
    "Jenkins v1 & v2": "/assets/img/tools/jenkins.png",
    uDeploy: "/assets/img/tools/uDeploy.png",
    Jira: "/assets/img/tools/jira.png",
    Azure: "/assets/img/tools/azure.png",
    Spacer: "/assets/img/tools/ampps.png",
  },
  "Dev Tools": {
    Git: "/assets/img/tools/git.png",
    Github: "/assets/img/tools/github.png",
    Gitlab: "/assets/img/tools/gitlab.png",
    Bitbucket: "/assets/img/tools/bitbucket.jpg",
    SourceTree: "/assets/img/tools/sourcetree.png",
    npm: "/assets/img/tools/npm.png",
    Webpack: "/assets/img/tools/webpack.png",
    babel: "/assets/img/tools/babel.png",
    ESLint: "/assets/img/tools/eslint.png",
    Gulp: "/assets/img/tools/gulp.png",
    Grunt: "/assets/img/tools/grunt.png",
    Torch: "/assets/img/tools/Torch.png",
    "Charles Proxy": "/assets/img/tools/charles.png",
    Spacer: "/assets/img/tools/ampps.png",
  },
  "UX/UI Tools": {
    Figma: "/assets/img/tools/figma.png",
    XD: "/assets/img/tools/xd.jpg",
    Zeplin: "/assets/img/tools/zeplin.png",
    Photoshop: "/assets/img/tools/photoshop.png",
    Spacer: "/assets/img/tools/ampps.png",
  },
  Testing: {
    Selenium: "/assets/img/skills/selenium.png",
    "Selenium IDE": "/assets/img/tools/se-ide.jpg",
    TestNG: "/assets/img/skills/testng.png",
    PyTest: "/assets/img/skills/python.png",
    "Webdriver IO": "/assets/img/skills/webdriverio.png",
    Mocha: "/assets/img/skills/mocha.png",
    Chai: "/assets/img/skills/chai.png",
    Gherkin: "/assets/img/skills/cucumber.png",
    Cucumber: "/assets/img/skills/cucumber.png",
    Galen: "./assets/img/skills/galen.png",
    JMeter: "/assets/img/tools/jmeter.png",
    Katalon: "/assets/img/tools/katalon.png",
    Applitools: "/assets/img/tools/applitools.png",
    Spacer: "/assets/img/tools/ampps.png",
  },
  WordPress: {
    "WordPress Foundation": "/assets/img/skills/wordpress.png",
    "ACF Pro": "/assets/img/tools/acf.png",
    "CPT UI": "/assets/img/tools/cpt.png",
    "Local by Flywheel": "/assets/img/tools/local.png",
    Ampps: "/assets/img/tools/ampps.png",
    Elementor: "/assets/img/skills/elementor.webp",
    Gutenberg: "/assets/img/skills/Gutenberg.jpeg",
    Spacer: "/assets/img/tools/ampps.png",
  },
};

export default tools;
