const tools = {
  Tools: {
    npm: "/assets/img/tools/npm.png",
    Webpack: "/assets/img/tools/webpack.png",
    babel: "/assets/img/tools/babel.png",
    "Jenkins v1 & v2": "/assets/img/tools/jenkins.png",
    Gulp: "/assets/img/tools/gulp.png",
    Grunt: "/assets/img/tools/grunt.png",
    Torch: "/assets/img/tools/Torch.png",
    "Charles Proxy": "/assets/img/tools/charles.png",
    uDeploy: "/assets/img/tools/uDeploy.png",
    FileZilla: "/assets/img/tools/filezilla.png",
    Zeplin: "/assets/img/tools/zeplin.png",
    Git: "/assets/img/tools/git.png",
    Github: "/assets/img/tools/github.png",
    Gitlab: "/assets/img/tools/gitlab.png",
    SourceTree: "/assets/img/tools/sourcetree.png",
    Jira: "/assets/img/tools/jira.png",
    Confluence: "/assets/img/tools/jira.png",
    Spacer: "/assets/img/tools/ampps.png",
  },
  Testing: {
    Selenium: "/assets/img/skills/selenium.png",
    "Selenium IDE": "/assets/img/tools/se-ide.jpg",
    TestNG: "/assets/img/skills/testng.png",
    PyTest: "/assets/img/skills/python.png",
    "Webdriver IO": "/assets/img/skills/webdriverio.png",
    Mocha: "/assets/img/skills/mocha.png",
    Chai: "/assets/img/skills/chai.png",
    Gherkin: "/assets/img/skills/cucumber.png",
    Cucumber: "/assets/img/skills/cucumber.png",
    Galen: "./assets/img/skills/galen.png",
    JMeter: "/assets/img/tools/jmeter.png",
    Katalon: "/assets/img/tools/katalon.png",
    Applitools: "/assets/img/tools/applitools.png",
    Spacer: "/assets/img/tools/ampps.png",
  },
  WordPress: {
    "WordPress CMS": "/assets/img/skills/wordpress.png",
    "WordPress Foundation": "/assets/img/skills/wordpress.png",
    "ACF Pro": "/assets/img/tools/acf.png",
    "CPT UI": "/assets/img/tools/cpt.png",
    "Local by Flywheel": "/assets/img/tools/local.png",
    Ampps: "/assets/img/tools/ampps.png",
    Spacer: "/assets/img/tools/ampps.png",
  },
  IDE: {
    "Visual Studio Code": "/assets/img/tools/vs-code.png",
    WebStorm: "/assets/img/tools/webstorm.png",
    PyCharm: "/assets/img/tools/pycharm.png",
    IntelliJ: "/assets/img/tools/intellij.png",
    Eclipse: "/assets/img/tools/eclipse.png",
    Netbeans: "/assets/img/tools/netbeans.png",
    Spacer: "/assets/img/tools/ampps.png",
  },
};

export default tools;
